[project]
name = "marimonotebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonpickle>=4.1.1",
    "matplotlib==3.10.8",
    "marimo>=0.19.11",
    "psycopg[binary]==3.3.2",
    "requests>=2.32.5",
]
